### ISSUE TITLE
maximum portability or the nicest goodies linux can offer

### ISSUE THREAD

**Issue by kerolasa** [traviscross/mtr#137]
I have sent couple changes, and to make future contributions to match with maintainer thinking I need clarification. There are many places where mtr appears to be portable, and that is in conflict with using some of the latest and greatest interfaces. For example use of signalfd() and eventfd() in combination with epoll() comes to my mind.

Obviously some of the modern linux interfaces will cause the mtr to have portability issue. But is that really an issue? Or is the future of this command in using gnulib and being as portable as possible? I do hope the answer is not 'do the both' because it is pretty difficult to lean towards both options and avoid regressions in various alternative compilation paths. And I have doubts anyone can maintain such mess.

**Comment by rewolff** [comment]
mtr can currently be compiled on Linux, MacOS and BSD. And quite possibly older unix-OSes like HPUX and SunOS. I would like to keep that portability. 

IF the code would simplify a lot when using the new interfaces, then I would lean towards having a "compatibility" file that emulates the new Linux interface for those OSes that don't have the new interface. 

But I don't think that using the newer interfaces is such a big benefit.

**Comment by kerolasa** [comment]
Sounds like leaning towards portability. That's ok. How about taking gnulib in use. I am not sure if you are familiar with it, but it really helps making software portable and simplify this project. For example the local copy of getopt_long() could be removed.

https://www.gnu.org/software/gnulib/
https://www.gnu.org/software/gnulib/manual/html_node/getopt_005flong.html

Here is another portability example, that no project should be willing to maintain alone.

https://www.gnu.org/software/gnulib/manual/html_node/calloc.html#calloc

**Comment by rewolff** [comment]
calloc is not a maintenance effort. Everybody knows how to write it 100% without bugs in one go. 

getopt is a more complicated issue. 
The problem is that when we depend on say gnulib, then besides the "has little communication with the outside world" function of "getopt" the library might also implement other stuff that pulls in another library which in turn.... and so on.

I've been bitten too often by dependency-hell. MTR has become a dependency hell. I can run bootstrap.sh on my server and then running configure on my workstation no longer works. And I'm distributing that configure script in the tarballs. Ugh! And the other way around, bootstrapping on my workstation somehow caused a 30 second delay in the build the first time, but now I try to reproduce that it suddenly behaves differently and is quick. 

Changes that move to glib, imho, should keep the compatibilty stuff we have now. The main code should be rewritten (if necessary) to use the standard calling conventions, but under an 
#ifndef GLIB
we should keep the compatibility we already have for those situations that lack an easy glib install. 

(If you want another cleanup task: How about standardizing on HAVE xxx macros instead of NO_CURSES vs IPINFO... All macros should move towards being the POSITIVE variant, so in the case of "NO_CURSES" the #ifdef would turn into #ifndef and vice versa. )

**Comment by kerolasa** [comment]
Thank you @rewolff for answers. I think this is guidance is enough for now.
