### ISSUE TITLE
Handle IP_DEST_HOST_UNREACHABLE / IP_DEST_PORT_UNREACHABLE replies on Cygwin.

### ISSUE THREAD

**Issue by kasper93** [traviscross/mtr#179]
Hi, 

Basically those ICMP replies are ignored and only `Unexpected ICMP result -1` is print on the stderr. mtr-packet than waits forever for response to the probe.

**Comment by kasper93** [comment]
@matt-kimball: I don't think the fix is correct. It does kill mtr on first `IP_DEST_HOST_UNREACHABLE` with error `mtr: No route to host`.  It shouldn't die.

**Comment by rewolff** [comment]
Oh! Now I understand.... I think the Linux version can/should be improved to report what is happening: The host at hop 9 is REPORTING that it doesn't have a route to the destination, that's something else altogether than the link from hop 8 to hop 9 being out-of-service.

**Comment by matt-kimball** [comment]
I wondered if exiting in response to a host unreachable response might be heavy handed.  @kasper93, is it actually causing problems for you, or do you just notice that it is different?

@rewolff, I agree that the Linux/Unix path should recognize "host unreachable" ICMP replies and report them in some way.  Right now it is ignoring them.

**Comment by kasper93** [comment]
>  @kasper93, is it actually causing problems for you, or do you just notice that it is different?

I don't understand the question. First of all mtr should behave the same for each platform as far as it is possible. And more importantly current behavior is just wrong. On Linux at least it doesn't end after first response. 

So now I see two separate issues
1. Windows version should not end if one hop response with "unreachable" message. After all there is 8 hops that are properly reported.
2. Both Windows and Linux version in fact ignore unreachable message in report. 

For reference see have WinMTR shows it. 

```
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                             192.168.0.1 -    0 |   17 |   17 |    0 |    0 |    1 |    0 |
...
|                         r1b.redefine.pl -    0 |   17 |   17 |    6 |    8 |   19 |    9 |
|                        Host Unreachable -  100 |   17 |    0 |    0 |    0 |    0 |    0 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR - 0.8. Copyleft @2000-2002 Vasile Laurentiu Stanimir  ( stanimir@cr.nivis.com )
```

> Oh! Now I understand.... I think the Linux version can/should be improved to report what is happening: The host at hop 9 is REPORTING that it doesn't have a route to the destination, that's something else altogether than the link from hop 8 to hop 9 being out-of-service.

Does it? Isn't it the case where hop 8 response that hop 9 in unreachable? At least last time I checked it was r1b.redefine.pl responding with that message. 

You can try yourself. Will probably get the same result as the problem is near destination. Host is `polsat.pl`

**Comment by matt-kimball** [comment]
Let me try rephrasing:  I think it is a bug that the Linux version doesn't behave like the Windows version.  The bug is that the Linux code path ignores ICMP host unreachable messages.  I propose that the Linux version report that the destination is unreachable and exit, just like the Windows version does.  You seem to object to this behavior.  What is the reason for your objection?  Understanding why you object -- beyond simply that it doesn't match the Linux version -- will help us all figure out what the right thing to do is.

Now, it is nicer, I suppose, if there is an in-line entry in the host list that says "Host Unreachable."  I do agree that approach seems more polished.

**Comment by kasper93** [comment]
> Now, it is nicer, I suppose, if there is an in-line entry in the host list that says "Host Unreachable." I do agree that approach seems more polished.

Now? When? I exactly suggest that this should report in-line and keep working. Instead just exit with an error message.

**Comment by matt-kimball** [comment]
"Now" was just a rhetorical phrasing for "I suppose I can see your point."

**Comment by kasper93** [comment]
Ah, ok :)

**Comment by rewolff** [comment]
MTR is a network diagnosis tool. Some people leave it running (in my case usually accidentally :-) )  for longer times. In that case ONE temporary "host is unreachable" should not exit the program. For a program like "ssh" trying to reach a host one "host unreachable" means that it's lost its purpose in life. To mtr the network errors, including the host unreachables, are the data it operates upon. 

In practice, people trying to diagnose problems might see a link disappear and a host reporting "unreachable" for a few seconds every day. A tool like mtr is useful in that it can help diagnose where such a problem occurs.

**Comment by matt-kimball** [comment]
You have convinced me that I was being dumb about this issue.  Of course mtr should carry on after a "host unreachable" packet.

However, the code @kasper93 is pointing at doesn't do what he thinks it does.  It is to handle "port unreachable" only for UDP probes which are sent to a port which is closed on the destination host.  In fact, "host unreachable" is completely ignored in the Unix path.  

I suggest that "host unreachable" ICMP messages be processed and reported in the Unix implementation of mtr-packet in the same way that the Cygwin implementation.  The problem is `handle_reply_errors` in `ui/cmdpipe.c` which reports the error and exits.  It should report the error back to the display code in a way which displays Host Unreachable in the same way that WinMTR does.

I have been planning to work on this, but haven't had time to give it attention yet.  If someone else has time to do this before I can get to it, that would great.  Otherwise, perhaps I can do this in a few weeks time.

**Comment by rewolff** [comment]
Thanks for the update. :-)
