### ISSUE TITLE
mtr built with ipv6 enabled doesn't work in ipv4 only env

### ISSUE THREAD

**Issue by arekm** [traviscross/mtr#19]
mtr (tested 0.84/0.85) fails if it was built with ipv6 support on a machine with ipv4 only availability:

mtr 12.12.12.12:

16870 socket(PF_INET, SOCK_DGRAM, IPPROTO_IP) = 5
16870 socket(PF_INET6, SOCK_DGRAM, IPPROTO_IP) = -1 EAFNOSUPPORT (Address family not supported by protocol)
16870 write(2, "Unable to allocate IPv6 socket for nameserver communication: Address family not supported by protocol\n", 102) = 10216870
exit_group(-1)                    = ?

It should check if ipv6 socket can be created and avoid using it if not (unless -6 was specified where it should fail in such case)

**Comment by sporkman** [comment]
I still see the behaviour with 0.86 on a FreeBSD host without IPv6.

**Comment by vpArth** [comment]
Why this issue is closed? Where can I get >0.85 version with fixed it? I use Ubuntu.
Can I clone and use this repo master branch?
At least terminal jamming fix required :(

**Comment by rewolff** [comment]
You need 
 sudo chown root.root ./mtr ; sudo chmod 4755 ./mtr
for it to get past the "unable to get raw socket". 

Alternatively to test it before doing that: 
 sudo ./mtr

**Comment by vpArth** [comment]
Hmm, it is absolutely different tool, isn't it?
It send 10 packets and print results, but 0.85 was realtime monitoring tool...

**Comment by rewolff** [comment]
Nope! 
mtr is "flexible". It will compile output modules only if you have the necessary files installed. If you don't have the necessary files installed, it will compile a "more basic" version. 

Try 
  apt-get build-dep mtr 
then it will install everything that was marked as "required for building mtr on your system", so that you will get a similarly configured mtr as your distribution had.
