### ISSUE TITLE
mtr-0.92 broken on NetBSD

### ISSUE THREAD

**Issue by 0-wiz-0** [traviscross/mtr#205]
mtr-0.87 worked fine on NetBSD.
With 0.92, I see:
````
# mtr google.com
mtr: Failure to start mtr-packet: invalid argument
````
(See also http://gnats.netbsd.org/52323)

**Comment by rewolff** [comment]
This is probably due to mtr not being able to find mtr-packet. With mtr-packet installed in the path, you should be able to run mtr again. 

With a bit of luck I've patched mtr to search for mtr-packet in the same directory as where it itself was found. You could try the latest git version and see if that works for you. 

mtr-packet helps with the privilege separation: the mtr-suite requires raw-network-access and therefore might run with root privileges, while there are also large external GUI libraries linked with mtr. To prevent a bug in those libraries resulting in a privilege escalation hole, we've introduced mtr-packet as the part that requires elevated privileges, while the main mtr-program that links with the gui libraries is not privileged. .

**Comment by 0-wiz-0** [comment]
Thanks for the explanation. It was my fault: the package had a manual install rule and that did not include mtr-packet. I switched it to use the default installation you provide and that works.
A different bug popped up, I'll report that separately.
