### ISSUE TITLE
Is the delivery rate too high triggering "Probes exhausted"? mtr_ver0.92.85

### ISSUE THREAD

**Issue by q158073378252010** [traviscross/mtr#298]
```
$ ./mtr -i 0.001 -n 192.168.100.1
./mtr: Probes exhausted
```
It seems that there will be no such problem in the 0.87 version.

**Comment by rewolff** [comment]
Suppose the target is a hop on the internet, say 10 hops away, then your commandline would result in sending out 10000 packets per second. 

mtr does not believe in setting arbitrary limits that are reasonable at the time they are programmed but then may "age" with the improvement of computer technology. So when I first worked on mtr, sending more than about 10 packets per second was not reasonable. We've improved on that by a factor of ten and mtr has not attempted to limit attempts to do so. 

Anyway, when you try "extreme" things like sending manymany packets, you might run into "that can't be done" messages from other parts of the system. In this case, mtr seems to run out of slots and reports this. It is possible that 0.87 ran into some other throttle that prevented this from happening.

It is not unreasonable that you run into an error condition if you try unreasonable things.

**Comment by k79e** [comment]
With 0.1 still run into this. But it runs for some seconds

**Comment by mystica555** [comment]
I don't know what changed in kernels, or MTR, but I used to be able to do the following:
(potentially sudo) mtr 75.75.75.75 
i 0.01
dd
to show the nice, very fast updating graph of pings to Comcast's DNS server. 

It used to run for hours if I let it. Now it dies after 10s or less. 

So what changed?

**Comment by rewolff** [comment]
Yoiu REALLY shouldn't be doing that  "for hours". If it is 5 hops to that server, you're sending and recieving 500 packets per second. Sure modern computers and networks can handle that much traffic, but to do that just for a "fast updating graph" that you're not watching 99% of the time is just wasteful.

**Comment by mystica555** [comment]
I don't think I ever let it go that long more than once when I forgot.. but now it dies in like 5 seconds.
The initial reason I wanted 0.01 interval with 10 hops to the DNS server from my house, was to get 1ms resolution and see if my crappy Puma6 cable modem was having a bad day (and indeed, it was) but it just dying after too short of a timeout bothers me now.

**Comment by stefanct** [comment]
This problem also happens with version 0.95 when using `-i 0.1` in about 5 seconds (and 10s for 0.2 intervals) if the remote host is down (unreachable in LAN). I found this, however, only after a real-world use case where the device locked up during episodes of "fast" pings and finding this report.

The problem is alleviated by setting `-Z 1` while using `-G` does not seem to have an effect on the time till the "probes" run out. The manpage does not mention the default values and I was too lazy to look them up in the source. Anyway, I think these limits are unrealistically low for actual use cases and I would like you to reconsider your decision.
