### ISSUE TITLE
Error opening terminal: cygwin

### ISSUE THREAD

**Issue by Debrovski** [traviscross/mtr#299]
Hello, Creator!
60e5c5c hash for mtr
3.0.6(0.338/5/3) for Cygwin x64
mtr launches successfully from Cygwin Terminal, but double-clicking at mtr.exe returns "Error opening terminal: cygwin"
I am not lazy, spended 14+ hours in Google, but failed to find a solution. Possible coz of my low Linux experience. My Sherlok says like i just miss something elementary...
Any help will be appreciated! I am really frustrated

**Comment by matt-kimball** [comment]
I recommend you run mtr from the command line, not by double clicking mtr.exe.

The problem here is that because of mtr's Unix heritage, it uses a system called termcap to display its output, and termcap needs data files describing how to write that output to the display.  The error you are getting is because it can't locate those files.

I've got some Windows binaries of mtr built here:  https://github.com/matt-kimball/mtr/releases
Those builds have a batch file, mtr.bat, which will set the path to the termcap files correctly.  With those, you can double click on mtr.bat, and it will run.  However, I still don't think it will be very useful to you, because without specifying a hostname on the commandline, you'll only get a trace to your local machine.

Future improvements to mtr might be to remove the dependency on termap for the Windows build and to prompt for a hostname if one isn't specified on the command line.  But no one has implemented those yet.

**Comment by Debrovski** [comment]
Amazing, Matt! That is what I needed!
 I can just create a shortcut to mtr.bat and define hostname as parameter. Now I am gonna copy it to USB-drive and  visit my friend to find the culprit of his random annoying  disconnections from World of Warcraft\Escape from Tarkov master-servers before he throws his computer out the window or kills somebody in ISP's office
