### ISSUE TITLE
mtr starts but no data is displayed

### ISSUE THREAD

**Issue by speedstercamaro** [traviscross/mtr#301]
I have Ubuntu running on Windows 10, I want to run mtr to diagnose packet loss along hops in traceroute. I run Ubuntu as administrator and type in sudo mtr "hostName". It looks like mtr opens but no data ever displays. It just shows the headings but it appears no packets are sent. I've included a screen grab.

![CaptureMTR](https://user-images.githubusercontent.com/50690539/57975658-e585bd00-7981-11e9-95d1-195dbfc05ec4.PNG)

**Comment by matt-kimball** [comment]
I assume you are using Windows Subsystem for Linux?

Last time I checked, raw sockets opened using WSL version 1 don't receive ICMP TTL expired packets.  Those packets are required for mtr to work.  Based on my understanding of how WSL version 2 works, I think this may be fixed, but I haven't been able to test with it yet.  WSL version 2 is supposed to be released next month, June 2019.  

In the meantime, I suggest you use the Cygwin version of mtr instead of the WSL version of mtr.  You can find precompiled binaries here:  https://github.com/matt-kimball/mtr/releases

**Comment by speedstercamaro** [comment]
Yes I am using the Windows Subsystem for Linux. I can wait till version 2 comes out and try it then.
