### ISSUE TITLE
mtr terminates with "no route to host"

### ISSUE THREAD

**Issue by tomjaguarpaw** [traviscross/mtr#357]
I generally keep `mtr` running in a desktop window in case I need to look at it for diagnostic purposes.  I suppose that occasionally my network loses connectivity because regularly after a few hours mtr terminates with "mtr: No route to host".  This is rather annoying, because this is exactly the kind of issue I am using mtr to provide diagnostics for! I don't want it to stop running at this point.  Is there something I can do to keep mtr alive and running even when there's no route to host?

I am running mtr with the command line `mtr  -t <my vps> --interval 1 --displaymode 1` and it is version `mtr 0.92` (on Debian Stable).

**Comment by zatricky** [comment]
By terminate do you specifically mean it is quitting to terminal with that error?

I noticed today that I get that in the output but it doesn't quit. For example I might have 12 hops showing with data ; hop 2 lost connectivity at some point and so hops 3-12 just "disappear" and never return, even though hop 2's connectivity was restored hours ago. :-/

If it's a different problem then I can create a separate issue.

**Comment by tomjaguarpaw** [comment]
> By terminate do you specifically mean it is quitting to terminal with that error?

It is both qutting to the terminal and it is showing that error.  I suppose I don't know for certain that they happen at the same time because I leave `mtr` unattended for long periods, but when I come back it is generally showing `mtr: No route to host` and it has quit to the terminal.

**Comment by rewolff** [comment]
I think the "quit-to-commandline" was fixed some time in the past: You need a recent version to get that fix. 

Current situation is that if the route goes dead at a certain point the screen is redrawn to delete the previous hops beyond the broeken route. Then when it comes back, mtr does not recover and starts doing weird things. This is my observations from the following experiment: 

start mtr on an internal machine, to say 8.8.8.8 (that's what I used) . Confirm it works. Now, on the router, create a fake route to that target that doesn't work. I used **route add -host 8.8.8.8 <my eth0>** (my router runs Linux). Now after a few seconds (the arp timeout) the router will start responding with host unreachable messages. Once mtr picks up on that you can **route del 8.8.8.8"  to see what happens when the route returns. 

Hopefully now everybody can recreate this on short notice, someone has the time to dive in and fix it. (Me: complete out of round tuits for now).

**Comment by zatricky** [comment]
Hopefully @tomjaguarpaw can confirm the newer version fixes that bit. I feel like I hijacked his issue. :-|

**Comment by tomjaguarpaw** [comment]
Yes, the latest git master (v0.93.56-f9df) works fine, thanks.
