### ISSUE TITLE
GTK3 UI doesn't refresh target when launched without a target

### ISSUE THREAD

**Issue by mikelolasagasti** [traviscross/mtr#378]
If mtr is launched with `mtr -g www.google.com` and then change the target in the UI, it works and data of the new target is reported.

If mtr is launched with `mtr -g` and then change the target in the UI interface, it doesn't change target and reports nothing.

Tested with 0.94 and master in Fedora 33.

Example: https://www.youtube.com/watch?v=h-tcjw3f3Jo

**Comment by robert-scheck** [comment]
This issue is not GTK3 specific, but reproducible with GTK2, too

**Comment by krisl** [comment]
`./mtr localhost` has this problem, also
`./mtr 127.x.x.x` also has this problem
`./mtr <some_other_local_interface` appears to be ok.
Not sure if it just a gtk issue, or perhaps its not even sending the probes

**Comment by robert-scheck** [comment]
@krisl, thank you for the pointer!

I've now analyzed this, but I'm not sure how to fix it: The problem is that `net_reopen()` does neither reinitialize the source address itself nor the source address family (which `net_open()` initially does both). This means, if `mtr -g 127.0.0.1` is run, `mtr` tries to re-use the source address 127.0.0.1 for the next entered (non-loopback) destination, which obviously does not work (because you can not reach 1.1.1.1 from 127.0.0.1). However, as nowadays on most Linux distributions `mtr -g localhost` is equivalent to `mtr -g ::1`, `mtr` tries to re-use the source address ::1 for the next entered (non-loopback and/or possibly even IPv4) destination, which obviously does not work as well (because you can reach neither 2606:4700:4700::1111 nor 127.0.0.1 from ::1).

So, from my point of view, a complete testing scenario (once a fix is proposed) would be:

1. `mtr -g 127.0.0.1`, then switch in the GUI to `1.1.1.1` (or any other non-loopback IPv4 address)
2. `mtr -g 127.0.0.1`, then switch in the GUI to `2606:4700:4700::1111` (or any other non-loopback IPv6 address)
3. `mtr -g ::1`, then switch in the GUI to `2606:4700:4700::1111` (or any other non-loopback IPv6 address)
4. `mtr -g ::1`, then switch in the GUI to `1.1.1.1` (or any other non-loopback IPv4 address)

**Comment by krisl** [comment]
@robert-scheck awesome sleuthing!  I've made a pull request at https://github.com/traviscross/mtr/pull/393

**Comment by robert-scheck** [comment]
> 2. `mtr -g 127.0.0.1`, then switch in the GUI to `2606:4700:4700::1111` (or any other non-loopback IPv6 address)
> 4. `mtr -g ::1`, then switch in the GUI to `1.1.1.1` (or any other non-loopback IPv4 address)

I am sorry, but at least these two test cases do not work for me using #393, thus the patch is same incomplete like my own hackery. Please re-open this issue.

**Comment by krisl** [comment]
It looks like `ctl.af` is whats used to determine the address family to use, and it's set only once in `get_hostent_from_name` in `mtr.c`.
So we need to reset this.  Perhaps by calling `get_hostent_from_name` again or otherwise resetting `ctl.af`, or getting rid of a single global address family altogether and derive it directly from the addresses in use.
I'm wondering what the least invasive change here is..

https://github.com/traviscross/mtr/blob/943b2ff88975499e0813fa7a54f244968b8672df/ui/gtk.c#L249-L252
perhaps we can just set `ctl->af = addr->af` immediately before the call to `net_reopen`?

My ability to test this may be limited, but I'll have a look a little later
