### ISSUE TITLE
Differences between local and remote connection

### ISSUE THREAD

**Issue by dpalemes** [traviscross/mtr#438]
I installed local mtr, fixed the 403 error reported here, everything worked ok. When making a remote connection via SSH on the computer where mtr was implemented, the folder mtr does not appear inside Cygwin and I have to redo the step of running the following commands:

- _git clone https://github.com/traviscross/mtr.git
- ./bootstrap.sh && ./configure && make
- make install_

That way I can normally run the remote mtr. If I switch remote computer, I need to run again. If I use the same, it works. I don't know how to resolve this.

**Comment by rewolff** [comment]
That's a "using my own OS" kind of question. This has nothing to do with mtr.

**Comment by dpalemes** [comment]
> That's a "using my own OS" kind of question. This has nothing to do with mtr.

How not? If it happens on more than one machine different from the other it has to do with the MTR.

**Comment by rewolff** [comment]
The way I read the original question: 
You installed it on machine A and then from machine A ssh-ed into machine B and wondered why it wasn't installed on machine B. However assuming you're not THAT stupid, it seems likely that you're SSH-ing from machine B to machine A. 
How then machine A shows you a "clean" situation where you have to install mtr from the beginning: I have no clue. Maybe you get a different "view" of the system because of the different "login source" ? I don't know: That's something that Linux wouldn't do. It is something specific to windows, and I can't get my head around such things. Computers should not behave that way. I get a headache trying to understand windows. I try to stay as far as possible from that sort of "triggers a headache" stuff. 

Under cygwin shell do: 
**cat > test.sh
#!/bin/sh
echo hi**
^D
(the ^D means hit control-D). Now you should have your prompt back. 
Do 
**chmod 755 test.sh**
and then 
**./test.sh**
It should say "hi". 
Now try logging in over ssh and see if the "test.sh" is still there: Only the "./test.sh" should be necessary.
