### ISSUE TITLE
The path hop lost packet

### ISSUE THREAD

**Issue by zboboj** [traviscross/mtr#516]
![Uploading image.png…]()
AS the picture，when I use mtr to test www.qq.com, the path hop would loss packet,but when I use ping to test the same hop ,it was not loss.  what is happen, I can not understand.
thank you!

**Comment by rewolff** [comment]
MTR sends out packets to the specified destination but "special" so that after 1, 2 ... etc hops the router SHOULD say: "Sorry but this packet has been in transit too long, return to sender!". Once the number-of-allowed-hops counter is high enough, the host at the destination should respond as normal. 
It seems that mtr sends slightly different packets as "ping" so that the target host  responds differently to them. You can tweak what packets MTR sends with the commandline. 

Using "ping", "UDP" or "TCP" packets for the probes gives slightly different responses. Some work better than others in one situation and then worse in another. You seem to have found a situation where mtr-default is worse than "ping". 

If you look in the manual "ping" might be called "ICMP ECHO".
